name: Deploy ML service

on:
  push:
    branches:
      - main

jobs:
  create_model_endpoint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Run tests
        run: |
          echo "Installing astro cli"
          curl -sSL install.astronomer.io | sudo bash -s
          cd airflow
          echo "astro dev pytest"
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install deployment dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sagemaker
      - name: Create endpoint
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
        run: python -m src.utils.deploy_endpoint

          

